version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mahadevs123
      POSTGRES_DB: ai_trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mahadevs123@db:5432/ai_trading"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
